language: elixir
otp_release:
  - 17.0
  - 17.1
elixir:
  - 1.0.0-rc1
  - 1.0.0-rc2
  - 1.0.0
before_script:
  - "MIX_ENV=test mix do deps.get, compile"
after_success:
  - MIX_ENV=test mix coveralls.travis
